### ISSUE TITLE
Empty File

### ISSUE THREAD

**Issue by robeisenrich** [yashrathi-git/vimeo_downloader#6] opened 2021-08-06 22:48 UTC
When I attempt to download the file it returns that it is downloaded along with a file size. However, When I view the file in my directory it is empty. Have you ever seen this before?

The video is embedded but I do not believe it is private. 'https://player.vimeo.com/video/533751269'

**Comment by yashrathi-git** [comment] 2021-08-07 01:21
Hi, robeisenrich
By default vimeo-downloader, downloads the video in the current directory (where you call your script from). You can change behaviour using:
```py
from vimeo_downloader import Vimeo
best_stream = Vimeo('your URL').best_stream
best_stream.download(download_directory='path/to/directory')
```

**Comment by robeisenrich** [comment] 2021-08-07 01:51
My issue is not so much where the file is downloading but rather that its downloading an empty file. Testing the below code with other vimeo videos it works great. Just not sure why it is downloading an empty file here

` 
vimeo_url = 'https://player.vimeo.com/video/533751269'
v = Vimeo(url = vimeo_url
    
)

best_stream = v.best_stream
mp4_url = best_stream.direct_url

title = best_stream.title

## Download
best_stream.download()
`

**Comment by yashrathi-git** [comment] 2021-08-07 04:12
I am not sure what you mean by "empty file". I was unable to reproduce the issue.

**Comment by yashrathi-git** [comment] 2021-08-07 11:17
Hi @robeisenrich 
> My issue is not so much where the file is downloading but rather that its downloading an empty file

Do, you mean it don't have any contents, or the file doesn't exists?

**Comment by robeisenrich** [comment] 2021-08-07 15:55
My apologies, I mean that the file exists but it is not downloaded as a mp4 and has 0 size associated with it

File name | Date | Type | Size
video file | today | file | 0KB

Were you able to download the link as a mp4?

**Comment by yashrathi-git** [comment] 2021-08-07 16:30
I can't reproduce this with,
```py
from vimeo_downloader import Vimeo
vimeo_url = 'https://player.vimeo.com/video/533751269'
v = Vimeo(url = vimeo_url)
v.best_stream.download()
```
works, as expected for me. 

You can check you are using the latest version by:
```sh
pip install --upgrade vimeo-downloader
```

**Comment by robeisenrich** [comment] 2021-08-07 20:47
Thanks for all your help,

I think I figured it out. When leaving the filename field blank it saved an empty file. However, when I add in the filename parameter it saves as expected.

Thanks! Great package

**Comment by yashrathi-git** [comment] 2021-08-10 11:25
Alright I am glad it worked. I am not able to reproduce your issue, so I am closing this

**Closed as completed by yashrathi-git** 2021-08-10 11:25 UTC
